### ISSUE TITLE
question about damaged manuscripts

### ISSUE THREAD

**Issue by iDannyZacharias** [OnlineCriticalPseudepigrapha/Online-Critical-Pseudepigrapha#24]
One of the PssSol manuscripts is slightly damaged, with some missing initial letters and occasionally a missing word. Should I leave this in the transcription and just note it in the description?

**Comment by kmpenner** [comment]
Could you take a look at how this is handled in the DSS such as 1En or Amram to see if that’s helpful?

Sent from Outlook<https://aka.ms/qtex0l> on my phone
________________________________

**Comment by iDannyZacharias** [comment]
Thanks Ken. Following the Amram example, I will use […] to represent a missing word. But should I do the same just for a missing letter of a word?

Danny

**Comment by kmpenner** [comment]
I would think [.] would be appropriate for a single missing letter.

**Comment by iDannyZacharias** [comment]
Thanks

~Danny Zacharias~
Servant— Of my Creator and Redeemer
Husband— to Maria, the most beautiful girl in the world
Father— to Lex, Jack, Ella-Rose, & Hudson, the very joy of my heart
Professor— Acadia Divinity College
MeOnTheWeb— DannyZacharias.net
Twitter— @iDannyZacharias
